### ISSUE TITLE
Tidak bisa login user / login mandor

### ISSUE THREAD

**Issue by suryanto23** [Faayakhun/Final-Project-Backend#12]
Username dan password yang dimasukkan sudah benar, tetapi gagal di autentikasi dan tidak mendapat token

**Comment by Faayakhun** [comment]
sudah saya perbaiki,saya harus ganti token biar mandor dan user saat login ada bedanya

**Comment by suryanto23** [comment]
Okee siap gan @Faayakhun

**Comment by suryanto23** [comment]
Okee siap gan @Faayakhun sudah normal lagi
